FGASES_EU = 'EU_TYPE'
FGASES_NONEU = 'NONEU_TYPE'

FGASES_EU_GROUP_CODE = 'f-gases-eu'
FGASES_NONEU_GROUP_CODE = 'f-gases-noneu'
FGASES_GROUP_CODE = [FGASES_EU_GROUP_CODE, FGASES_NONEU_GROUP_CODE]

BDR_GROUP_CODE = 'ods-cars-vans'
