# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_representative_data_to_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
