# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(default='', max_length=64),
        ),
    ]
