# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_auto_20190628_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="check_passed",
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="year",
            field=models.PositiveSmallIntegerField(default=2020, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcycle",
            name="year",
            field=models.PositiveSmallIntegerField(db_index=True, default=2020),
        ),
    ]
