# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20200212_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcompany',
            name='current',
            field=models.NullBooleanField(default=False),
        ),
    ]
