# Generated by Django 3.2.4 on 2023-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_auto_20210622_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="year",
            field=models.PositiveSmallIntegerField(default=2023, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcycle",
            name="year",
            field=models.PositiveSmallIntegerField(db_index=True, default=2023),
        ),
    ]
