# Generated by Django 3.2.25 on 2025-04-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20230214_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, unique=True),
        ),
        migrations.AlterField(
            model_name='cycleemailtemplate',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='cyclenotification',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='historicalcycle',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2025),
        ),
        migrations.AlterField(
            model_name='historicalcycleemailtemplate',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
